name: Build_APK

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Buildozer-Kivy-Apk-Creator
        uses: wildspider57389928/Buildozer-Kivy-APK_Creator@1.0.0
   
